import { Node, Edge, MarkerType } from '@xyflow/react';

export const INITIAL_NODES: Node[] = [
  // Gateway CEO
  {
    id: 'hermes',
    type: 'agentNode',
    position: { x: 500, y: 30 },
    data: {
      slug: 'hermes',
      name: 'Hermes Master Gateway (CEO)',
      role: 'CEO_GATEWAY',
      agentType: 'gateway',
      department: null,
      status: 'idle',
      isActive: true,
      model: 'Groq / Claude 3.7',
      toolsets: ['delegation'],
    },
  },

  // === MARKETING DEPARTMENT CLUSTER ===
  {
    id: 'cluster-marketing',
    type: 'departmentCluster',
    position: { x: 20, y: 170 },
    style: { width: 1220, height: 390 },
    data: {
      department: 'marketing',
      title: 'Ban Marketing & Nội Dung (CMO Unit)',
      agentCount: 5,
      isActive: true,
      isCollapsed: false,
      memberIds: [
        'hermes-marketing-lead',
        'mkt-researcher',
        'mkt-writer-01',
        'mkt-writer-02',
        'mkt-auditor',
        'tool-mkt-web',
        'tool-mkt-file',
      ],
    },
  },
  {
    id: 'hermes-marketing-lead',
    type: 'agentNode',
    parentId: 'cluster-marketing',
    position: { x: 30, y: 65 },
    data: {
      slug: 'hermes-marketing-lead',
      name: 'CMO Marketing Lead',
      role: 'department_lead',
      agentType: 'department_lead',
      department: 'marketing',
      status: 'idle',
      isActive: true,
      toolsets: ['delegation', 'web', 'file'],
    },
  },
  {
    id: 'mkt-researcher',
    type: 'agentNode',
    parentId: 'cluster-marketing',
    position: { x: 290, y: 65 },
    data: {
      slug: 'mkt-researcher',
      name: 'Market Researcher Sub-Agent',
      role: 'researcher',
      agentType: 'sub_agent',
      department: 'marketing',
      status: 'idle',
      isActive: true,
      toolsets: ['web', 'file'],
    },
  },
  // Attached Tools for Researcher
  {
    id: 'tool-mkt-web',
    type: 'toolSlotNode',
    parentId: 'cluster-marketing',
    position: { x: 290, y: 285 },
    data: {
      toolType: 'web',
      name: 'Google Search & Web Scraper',
      description: 'Tìm kiếm dữ liệu thị trường và cào nội dung tham khảo',
      parentAgentSlug: 'mkt-researcher',
    },
  },
  {
    id: 'tool-mkt-file',
    type: 'toolSlotNode',
    parentId: 'cluster-marketing',
    position: { x: 440, y: 285 },
    data: {
      toolType: 'file',
      name: 'Knowledge Vector Storage',
      description: 'Lưu trữ tài liệu và insight vào CRM DB',
      parentAgentSlug: 'mkt-researcher',
    },
  },
  {
    id: 'mkt-writer-01',
    type: 'agentNode',
    parentId: 'cluster-marketing',
    position: { x: 600, y: 65 },
    data: {
      slug: 'mkt-writer-01',
      name: 'Copywriter #1 (PAS/BAB)',
      role: 'copywriter',
      agentType: 'sub_agent',
      department: 'marketing',
      status: 'idle',
      isActive: true,
      toolsets: ['file'],
    },
  },
  {
    id: 'mkt-writer-02',
    type: 'agentNode',
    parentId: 'cluster-marketing',
    position: { x: 600, y: 225 },
    data: {
      slug: 'mkt-writer-02',
      name: 'Copywriter #2 (Case/Contrarian)',
      role: 'copywriter',
      agentType: 'sub_agent',
      department: 'marketing',
      status: 'idle',
      isActive: true,
      toolsets: ['file'],
    },
  },
  {
    id: 'mkt-auditor',
    type: 'agentNode',
    parentId: 'cluster-marketing',
    position: { x: 910, y: 65 },
    data: {
      slug: 'mkt-auditor',
      name: 'Brand Voice Auditor Sub-Agent',
      role: 'auditor',
      agentType: 'sub_agent',
      department: 'marketing',
      status: 'idle',
      isActive: true,
      toolsets: ['file'],
    },
  },

  // === SALES DEPARTMENT CLUSTER (Inactive / Greyed Out) ===
  {
    id: 'cluster-sales',
    type: 'departmentCluster',
    position: { x: 20, y: 560 },
    style: { width: 575, height: 430 },
    data: {
      department: 'sales',
      title: 'Ban Kinh Doanh & Sales',
      agentCount: 4,
      isActive: false,
      isCollapsed: false,
      memberIds: ['hermes-sales-lead', 'sales-lead-scorer', 'sales-chat-advisor', 'sales-quotation-drafter'],
    },
  },
  {
    id: 'hermes-sales-lead',
    type: 'agentNode',
    parentId: 'cluster-sales',
    position: { x: 30, y: 120 },
    data: {
      slug: 'hermes-sales-lead',
      name: 'Head of Sales Lead',
      role: 'department_lead',
      agentType: 'department_lead',
      department: 'sales',
      status: 'idle',
      isActive: false,
      toolsets: ['delegation', 'http_tool'],
    },
  },
  {
    id: 'sales-lead-scorer',
    type: 'agentNode',
    parentId: 'cluster-sales',
    position: { x: 300, y: 50 },
    data: {
      slug: 'sales-lead-scorer',
      name: 'Lead Scoring Sub-Agent',
      role: 'scorer',
      agentType: 'sub_agent',
      department: 'sales',
      status: 'idle',
      isActive: false,
      toolsets: ['http_tool'],
    },
  },
  {
    id: 'sales-chat-advisor',
    type: 'agentNode',
    parentId: 'cluster-sales',
    position: { x: 300, y: 175 },
    data: {
      slug: 'sales-chat-advisor',
      name: 'Chat Sales Advisor Sub-Agent',
      role: 'advisor',
      agentType: 'sub_agent',
      department: 'sales',
      status: 'idle',
      isActive: false,
      toolsets: ['web'],
    },
  },
  {
    id: 'sales-quotation-drafter',
    type: 'agentNode',
    parentId: 'cluster-sales',
    position: { x: 300, y: 300 },
    data: {
      slug: 'sales-quotation-drafter',
      name: 'Quotation Drafter Sub-Agent',
      role: 'drafter',
      agentType: 'sub_agent',
      department: 'sales',
      status: 'idle',
      isActive: false,
      toolsets: ['http_tool', 'file'],
    },
  },

  // === TECH DEPARTMENT CLUSTER (Inactive / Greyed Out) ===
  {
    id: 'cluster-tech',
    type: 'departmentCluster',
    position: { x: 625, y: 560 },
    style: { width: 575, height: 430 },
    data: {
      department: 'tech',
      title: 'Ban Kỹ Thuật & Dự Án',
      agentCount: 3,
      isActive: false,
      isCollapsed: false,
      memberIds: ['hermes-tech-lead', 'tech-estimator', 'tech-code-reviewer'],
    },
  },
  {
    id: 'hermes-tech-lead',
    type: 'agentNode',
    parentId: 'cluster-tech',
    position: { x: 30, y: 120 },
    data: {
      slug: 'hermes-tech-lead',
      name: 'CTO / Tech Lead',
      role: 'department_lead',
      agentType: 'department_lead',
      department: 'tech',
      status: 'idle',
      isActive: false,
      toolsets: ['delegation', 'http_tool'],
    },
  },
  {
    id: 'tech-estimator',
    type: 'agentNode',
    parentId: 'cluster-tech',
    position: { x: 300, y: 80 },
    data: {
      slug: 'tech-estimator',
      name: 'Tech Estimator Sub-Agent',
      role: 'estimator',
      agentType: 'sub_agent',
      department: 'tech',
      status: 'idle',
      isActive: false,
      toolsets: ['file'],
    },
  },
  {
    id: 'tech-code-reviewer',
    type: 'agentNode',
    parentId: 'cluster-tech',
    position: { x: 300, y: 240 },
    data: {
      slug: 'tech-code-reviewer',
      name: 'Code Quality Reviewer Sub-Agent',
      role: 'reviewer',
      agentType: 'sub_agent',
      department: 'tech',
      status: 'idle',
      isActive: false,
      toolsets: ['file'],
    },
  },
];

export const INITIAL_EDGES: Edge[] = [
  // CEO Gateway -> Leads
  {
    id: 'e-hermes-marketing',
    source: 'hermes',
    target: 'hermes-marketing-lead',
    type: 'animatedAgentEdge',
    animated: true,
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#a855f7', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#a855f7' },
  },
  {
    id: 'e-hermes-sales',
    source: 'hermes',
    target: 'hermes-sales-lead',
    type: 'animatedAgentEdge',
    data: { department: 'sales', status: 'idle' },
    style: { stroke: '#64748b', strokeWidth: 1.5, strokeDasharray: '4 4' },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#64748b' },
  },
  {
    id: 'e-hermes-tech',
    source: 'hermes',
    target: 'hermes-tech-lead',
    type: 'animatedAgentEdge',
    data: { department: 'tech', status: 'idle' },
    style: { stroke: '#64748b', strokeWidth: 1.5, strokeDasharray: '4 4' },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#64748b' },
  },

  // Marketing Pipeline: Lead -> Researcher -> Writers -> Auditor
  {
    id: 'e-mkt-lead-researcher',
    source: 'hermes-marketing-lead',
    target: 'mkt-researcher',
    type: 'animatedAgentEdge',
    animated: true,
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#a855f7', strokeWidth: 2 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#a855f7' },
  },
  // Researcher Sub-Tool connections (dashed curved lines)
  {
    id: 'e-researcher-tool-web',
    source: 'mkt-researcher',
    target: 'tool-mkt-web',
    type: 'animatedAgentEdge',
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#10b981', strokeWidth: 1.2, strokeDasharray: '4 4' },
  },
  {
    id: 'e-researcher-tool-file',
    source: 'mkt-researcher',
    target: 'tool-mkt-file',
    type: 'animatedAgentEdge',
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#f59e0b', strokeWidth: 1.2, strokeDasharray: '4 4' },
  },
  {
    id: 'e-mkt-researcher-writer1',
    source: 'mkt-researcher',
    target: 'mkt-writer-01',
    type: 'animatedAgentEdge',
    animated: true,
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#3b82f6', strokeWidth: 1.5 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#3b82f6' },
  },
  {
    id: 'e-mkt-researcher-writer2',
    source: 'mkt-researcher',
    target: 'mkt-writer-02',
    type: 'animatedAgentEdge',
    animated: true,
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#3b82f6', strokeWidth: 1.5 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#3b82f6' },
  },
  {
    id: 'e-mkt-writer1-auditor',
    source: 'mkt-writer-01',
    target: 'mkt-auditor',
    type: 'animatedAgentEdge',
    animated: true,
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#ec4899', strokeWidth: 1.5 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#ec4899' },
  },
  {
    id: 'e-mkt-writer2-auditor',
    source: 'mkt-writer-02',
    target: 'mkt-auditor',
    type: 'animatedAgentEdge',
    animated: true,
    data: { department: 'marketing', status: 'idle' },
    style: { stroke: '#ec4899', strokeWidth: 1.5 },
    markerEnd: { type: MarkerType.ArrowClosed, color: '#ec4899' },
  },

  // Sales Sub-Agents
  {
    id: 'e-sales-lead-scorer',
    source: 'hermes-sales-lead',
    target: 'sales-lead-scorer',
    type: 'animatedAgentEdge',
    data: { department: 'sales', status: 'idle' },
    style: { stroke: '#64748b', strokeDasharray: '4 4' },
  },
  {
    id: 'e-sales-lead-advisor',
    source: 'hermes-sales-lead',
    target: 'sales-chat-advisor',
    type: 'animatedAgentEdge',
    data: { department: 'sales', status: 'idle' },
    style: { stroke: '#64748b', strokeDasharray: '4 4' },
  },
  {
    id: 'e-sales-lead-drafter',
    source: 'hermes-sales-lead',
    target: 'sales-quotation-drafter',
    type: 'animatedAgentEdge',
    data: { department: 'sales', status: 'idle' },
    style: { stroke: '#64748b', strokeDasharray: '4 4' },
  },

  // Tech Sub-Agents
  {
    id: 'e-tech-lead-estimator',
    source: 'hermes-tech-lead',
    target: 'tech-estimator',
    type: 'animatedAgentEdge',
    data: { department: 'tech', status: 'idle' },
    style: { stroke: '#64748b', strokeDasharray: '4 4' },
  },
  {
    id: 'e-tech-lead-reviewer',
    source: 'hermes-tech-lead',
    target: 'tech-code-reviewer',
    type: 'animatedAgentEdge',
    data: { department: 'tech', status: 'idle' },
    style: { stroke: '#64748b', strokeDasharray: '4 4' },
  },
];
